#!/bin/sh

set -e

cat <<EOF > /usr/share/nginx/html/runtime-config.js
window.RUNTIME_CONFIG = {
  FRONTEND_WEBCAPTIONER_SERVER:                  "${FRONTEND_WEBCAPTIONER_SERVER}",
  FRONTEND_YOUTUBE_REGION:                       "${FRONTEND_YOUTUBE_REGION}",
  FRONTEND_DEFAULT_SOTRA_MODEL:                  "${FRONTEND_DEFAULT_SOTRA_MODEL}",
  FRONTEND_DEFAULT_YOUTUBE_TIME_OFFSET:          "${FRONTEND_DEFAULT_YOUTUBE_TIME_OFFSET}",
  FRONTEND_MAX_LINES_IN_HISTORY:                 "${FRONTEND_MAX_LINES_IN_HISTORY}",
  FRONTEND_DEFAULT_VOSK_SAMPLE_RATE:             "${FRONTEND_DEFAULT_VOSK_SAMPLE_RATE}",
  FRONTEND_RECORDING_INFORMATION_LINE:           "${FRONTEND_RECORDING_INFORMATION_LINE}",
  FRONTEND_DEFAULT_AUDIO_FORMAT:                 "${FRONTEND_DEFAULT_AUDIO_FORMAT}",
  FRONTEND_SEND_TIMESTAMP:                       "${FRONTEND_SEND_TIMESTAMP}",
  FRONTEND_SEND_TIMESTAMP_COUNT:                 "${FRONTEND_SEND_TIMESTAMP_COUNT}",
  FRONTEND_DEFAULT_TRANSLATION_TARGET_LANGUAGE:  "${FRONTEND_DEFAULT_TRANSLATION_TARGET_LANGUAGE}",
};
EOF

exec nginx -g "daemon off;"
